<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $prismicModel \Marleen\PrismicIntegration\ViewModel\Prismic
 * @var $documentModel \Marleen\PrismicIntegration\ViewModel\Document
 */

// Get documentModel
$documentModel = $block->getData('documentModel');
// Get document from Elgentos module
$document = $documentModel->getDocument();
if ($document !== null) {
    // Get slices from document
    $slices = $document->data->slices ?? [];
    $prismicModel = $block->getData('prismicModel');
    // Display the slices using the Prismic model's displaySlices method
    echo $prismicModel->displaySlices($slices, $block);
}
