<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $escaper \Magento\Framework\Escaper
 * @var $slice Marleen\PrismicIntegration\Model\Slices\HeroSliceInterface
 * @var $block \Magento\Framework\View\Element\Template
 */

$sliceBlock = $block->getData('slice');
$text = $sliceBlock->getText();
$background = $sliceBlock->getBackgroundImage();
$variation = $block->getData('blockVariation');
$buttonText = $sliceBlock->getButtonText();
$buttonLink = $sliceBlock->getButtonLink();

if(!empty($background->url) && !empty($text)):
?>
    <section class="relative">
        <figure class="absolute inset-0">
            <img src="<?= $escaper->escapeHtmlAttr($background->url) ?>" class="pointer-events-none select-none object-cover h-[300px] md:h-full w-full" alt="">
        </figure>
        <div class="relative flex justify-center bg-hero w-full">
            <div class="flex flex-col justify-end items-end h-[300px] md:h-[500px]">
                <h2 class="text-white max-w-[1126px] text-3xl md:text-7xl text-center title-shadow mb-5 mx-10 md:mx-20"><?= $escaper->escapeHtml($text) ?></h2>
                <?php if($variation == 'heroWithButton' && !empty($buttonText) && !empty($buttonLink)): ?>
                    <a class="button mb-5 mx-auto"
                        href=" <?= $escaper->escapeHtmlAttr($buttonLink->url) ?>"><?= $escaper->escapeHtml($buttonText) ?>
                    </a>
                <?php endif; ?>
            </div>
        </div>
    </section>
<?php
endif;
?>

